"""detect data from image

Revision ID: 0fe39c244f84
Revises: eec0a313ae53
Create Date: 2020-07-08 19:05:05.757381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe39c244f84'
down_revision = 'eec0a313ae53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detect_data', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detect_data', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detect_data', type_='foreignkey')
    op.drop_column('detect_data', 'image_id')
    # ### end Alembic commands ###
