"""'followers'

Revision ID: 30abf1816e15
Revises: 7abd9b3046d7
Create Date: 2020-04-08 20:38:26.980881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30abf1816e15'
down_revision = '7abd9b3046d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
