"""detected data from image

Revision ID: 8cd914ce3129
Revises: 0fe39c244f84
Create Date: 2020-07-08 19:19:04.644022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd914ce3129'
down_revision = '0fe39c244f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detect_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_index', sa.Integer(), nullable=True),
    sa.Column('predicted_class', sa.String(length=120), nullable=True),
    sa.Column('obj_score', sa.Float(), nullable=True),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.Column('bottom', sa.Integer(), nullable=True),
    sa.Column('all_score', sa.PickleType(), nullable=True),
    sa.Column('multiple_obj', sa.PickleType(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detect_data')
    # ### end Alembic commands ###
